config/routes.rb
Rails.application.routes.draw do
  get 'api/stations'
  resources :trips
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  attr_writer :from_time, :to_time, :departure_date
  validates :from_time, presence: true
  validates :to_time, presence: true
  validates :departure_station, presence: true
  validates :arrival_station, presence: true
  validates :from_date, presence: true
  validates :to_date, presence: true
  validate :departure_station_existance, :arrival_station_existance
  validate :check_dates

  def save_dates
    from_date = create_date(departure_date, from_time)
    to_date = create_date(departure_date, to_time)
    write_attribute(:from_date, from_date)
    write_attribute(:to_date, to_date)
  end

  def departure_date
    from_date&.strftime('%d/%m/%Y')
  end

  def from_time
    from_date
  end

  def to_time
    to_date
  end

  def departure_station_existance
    return if TrainStationService.station_exists?(departure_station)

    errors.add(:departure_station, "- #{departure_station} is not a valid departure station")
  end

  def arrival_station_existance
    return if TrainStationService.station_exists?(arrival_station)

    errors.add(:arrival_station, "- #{arrival_station} is not a valid arrival station")
  end

  def check_dates
    return if from_date.nil? || to_date.nil? || departure_date.nil?

    if from_date > to_date
      errors.add(:from_time, '- the from date must finish after the from date')
    elsif from_date == to_date
      errors.add(:to_time, '- To time must be after from time')
    elsif from_date < DateTime.now || to_date < DateTime.now
      errors.add(:departure_date, '- The departure date must be in future')
    end
  end

  def create_date(date, time)
    d = Date.strptime(date, '%d/%m/%Y')
    DateTime.new(d.year, d.month, d.day, time[3].to_i, time[4].to_i)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :tgvmax_key,
            format: { with: /HC[0-9]{9}/, message: ' - Enter a correct TGVMAX key like HC123456789' },
            on: :update
  validate :validate_age, on: :update

  def tgvmax_key_valid?
    tgvmax_key&.match(/^HC[0-9]{9}$/)
  end

  private

  def validate_age
    return if birthdate.present? && birthdate < 16.years.ago && birthdate > 28.years.ago

    errors.add(:birthdate, ': You should be between 16 and 27 years old') 
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  # GET /api/trips
  def stations
    render json: TrainStationService.search(api_params['q'])
  end

  private

  def api_params
    params.permit(:q)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:tgvmax_key, :birthdate, :email, :password,
               :current_password, :password_confirmation)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit update destroy]
  before_action :check_user, only: %i[show edit update destroy]
  before_action :check_tgvmax_key, only: %i[new update]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.where(user_id: current_user.id).order('from_date')
  end

  # GET /trips/1
  # GET /trips/1.json
  def show; end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit; end

  # POST /trips
  # POST /trips.json
  def create
    puts 'trip', trip_params
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    @trip.searching = true
    @trip.from_date = from_date
    @trip.to_date = to_date

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    puts 'trip', trip_params
    respond_to do |format|
      @trip.from_date = from_date
      @trip.to_date = to_date
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def from_date
    departure_date = trip_params[:departure_date]
    from_time = trip_params.select { |k| k.start_with? 'from_time' }.values
    return if departure_date.nil? || departure_date.empty? || from_time.length != 5

    @trip.create_date(departure_date, from_time)
  end

  def to_date
    departure_date = trip_params[:departure_date]
    to_time = trip_params.select { |k| k.start_with? 'to_time' }.values
    return if departure_date.nil? || departure_date.empty? || to_time.length != 5

    @trip.create_date(departure_date, to_time)
  end

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def check_user
    redirect_to trips_path if current_user != @trip.user
  end

  def trip_params
    params.require(:trip).permit(:user_id, :departure_station, :arrival_station, :from_date, :to_date, :searching,
                                 :from_time, :to_time, :departure_date)
  end

  def check_tgvmax_key
    return if current_user.tgvmax_key_valid?

    redirect_to edit_user_registration_path, flash: { alert: 'You must enter a valid TGVMAX Key' }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
  def searching_background_color(trip)
    'has-background-success' if trip.searching
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "Trips", trips_path, class: "navbar-item" %>
      <!-- <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div> -->
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if !user_signed_in? %>
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-primary has-text-white" %>
          <%= link_to "Sign In", new_user_session_path, class: "button is-light" %>
        <% else %>
          <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= current_user.email %>
          </a>

          <div class="navbar-dropdown">
            <!-- choix de l'app -->
            <hr class="navbar-divider">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
          </div>
        </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/trips/_form.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css">
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
   integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
<%= simple_form_for(@trip) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <% if @trip.errors.present? %>
      <ul class="notification is-danger">
        <p class="has-text-weight-bold">Errors: </p>
        <% @trip.errors.messages.each do |e| %>
          <li><%= e.last.to_sentence %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="form-inputs">
    <%= f.input :departure_station, required: true, autofocus: true %>
    <%= f.input :arrival_station, required: true %>
    <%= f.input :departure_date, required: true %>
    <%= f.input :from_time, as: :time, default: Time.parse('7:00'), required: true %>
    <%= f.input :to_time, as: :time, default: Time.parse('18:00'), required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'is-primary' %>
  </div>
<% end %>

<script>
  $('#trip_departure_date').datepicker({
    dateFormat: "dd/mm/yy",
    minDate: 0,
    maxDate: 31,
  });
</script>

app/views/trips/edit.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/easy-autocomplete.min.css">


<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <h1 class="title is-size-1">Edit Trip</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="columns is-centered">
        <div class="column is-half">
            <%= render 'form', trip: @trip %>

            <%= link_to 'Show', @trip %> |
            <%= link_to 'Back', trips_path %>
        </div>
    </div>
</div>

app/views/trips/index.html.erb
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-vcentered">
        <div class="column">
          <h1 class="title is-size-1">Your Trips</h1>
        </div>
      </div>
    </div>
  </div>
</section>
<br>
<div class="container">
  <div class="columns is-centered">
    <div class="column is-two-thirds has-text-centered">
      <%= link_to 'Create New Trip', new_trip_path, class: "button is-primary has-space-around" %>
      <br>
      <table class="table is-size-7-mobile">
        <thead>
          <tr>
            <th>De</th>
            <th>À</th>
            <th>Date</th>
            <th class="is-hidden-mobile">Heure</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @trips.each do |trip| %>
            <tr class="<%= searching_background_color(trip) %>">
              <td><%= trip.departure_station %></td>
              <td><%= trip.arrival_station %></td>
              <td><%= trip.from_date.strftime('%d/%m/%y') if trip.from_date %></td>
              <td class="is-hidden-mobile"><%= trip.from_date.strftime('%HH%M') if trip.from_date %>-<%= trip.to_date.strftime('%HH%M') if trip.to_date %> </td>
              <td class="td-icon"><%= link_to '🔎', trip %></td>
              <td class="td-icon"><%= link_to '✏️', edit_trip_path(trip) %></td>
              <td class="td-icon"><%= link_to '❌', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<br>
</div>

app/views/trips/new.html.erb
<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <h1 class="title is-size-1">Create Trip</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<br>
<div class="columns is-centered">
    <div class="column is-half">
        <%= render 'form', trip: @trip %>
        <%= link_to 'Back', trips_path, class: "button" %>
    </div>
</div>

app/views/trips/show.html.erb
<section class="hero is-link">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-vcentered">
        <div class="column">
          <h1 class="title is-size-1">Your Trip</h1>
        </div>
      </div>
    </div>
  </div>
</section>
<br>
<div class="container">
<p>
  <strong>User:</strong>
  <%= @trip.user_id %>
</p>

<p>
  <strong>Departure station:</strong>
  <%= @trip.departure_station %>
</p>

<p>
  <strong>Arrival station:</strong>
  <%= @trip.arrival_station %>
</p>

<p>
  <strong>From date:</strong>
  <%= @trip.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @trip.to_date %>
</p>

<p>
  <strong>Searching:</strong>
  <%= @trip.searching %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip), class: "button is-primary is-small" %> 
<%= link_to 'Back', trips_path, class: "button is-small" %>
</div>